steps:
  - name: gcr.io/cloud-builders/gcloud
    args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/http-server:dev','gcr.io/$PROJECT_ID/http-server:prod']
timeout: 300s
tags: ['http-server-tag','${_ENV}']
