options:
  substitution_option: 'ALLOW_LOOSE'
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-east4-a
    - CLOUDSDK_CONTAINER_CLUSTER=cbd-mad-demo
    - ENV=${_ENV}
steps:
  - id: 'render http'
    name: gcr.io/$PROJECT_ID/skaffold:alpha
    args: ['render', '-f=skaffold.yaml', '--output=k8s-http-server.yaml']
    waitFor: ['-']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','k8s-http-server.yaml','gs://mad-demo-k8s/']
    waitFor: ['render http']
timeout: 100s
tags: ['http-server-render']
