apiVersion: v1
kind: Service
metadata:
  name: http-server
  labels:
    service: rest
    env: dev
    component: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    service: rest
    env: dev
    component: backend