replicaCount: 1
env: dev

image:
  repository: gcr.io/cloud-build-delivery-mad/http-server
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

resources: {}

envVar:
  grpcServerHost: grpc-server
  grpcServerPort: 8090

